name: release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: checkout
        run: git fetch --prune --unshallow
      - name: install environment
        run: pip install pipenv && pipenv sync -d 
      - name: test
        run: pipenv run make test
      - name: build
        run: pipenv run make build
      - name: upload to pypi
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{secrets.twine_password }}
          packages_dir: dist/
